variables:
  GOBIN:  "$(GOPATH)/bin" # Go binaries path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GO111MODULE: "on"
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)"
  bintrayRepo: solvingj/public-bin
  

trigger:
  tags:
    include: ['*']
jobs:
  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - script: go build -o envx.exe
        displayName: go_build
      - script: curl --help
        displayName: curl_test
      - script: curl
        displayName: cd
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')

# - job: Linux
  # pool:
    # vmImage: "ubuntu-16.04"
  # steps:
    # - script: curl -fL https://getcli.jfrog.io | sh
      # displayName: Install JFrog CLI
    # - script: ./jfrog --version
    

# - job: macOS
  # pool:
    # vmImage: "macOS-10.13"
  # steps:
    # - script: brew install jfrog-cli-go
      # displayName: Install JFrog CLI  
    # - script: jfrog --version

# - job: B
  # dependsOn: A
  # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  # steps:
  # - script: echo this only runs for master