variables:
  GOBIN:  "$(GOPATH)/bin" # Go binaries path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GO111MODULE: "on"
  MODULEPATH: "$(GOPATH)/src/github.com/$(build.repository.name)"
  BT_API: https://api.bintray.com/content
  BT_REPO: public-generic
  PROJECT_NAME: $(Build.SourceBranch)
  VERSION_TAG: $(Build.SourceBranchName)
  PLATFORM: $(System.Phasename)
  
trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
    
jobs:
  - job: windows_x64
    variables: 
      target_file: envx.exe
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - script: set
        displayName: set
      - script: echo %BUILD_SOURCEBRANCHNAME%
        displayName: echo BUILD_SOURCEBRANCHNAME
        condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')
      - script: >-
          echo "
          curl -T $(target_file) 
          -u$(BT_USER):$(BT_KEY) 
          $(BT_API)/
          $(BT_USER)/
          $(BT_REPO)/
          $(PROJECT_NAME)/
          $(VERSION_TAG)/
          $(PLATFORM)"
        displayName: bintray_publish
        condition: succeeded()

# - job: linux_x64
  # pool:
    # vmImage: "ubuntu-16.04"
  # steps:
    # - script: curl -fL https://getcli.jfrog.io | sh
      # displayName: Install JFrog CLI
    # - script: ./jfrog --version
    

# - job: macos_x64
  # pool:
    # vmImage: "macOS-10.13"
  # steps:
    # - script: brew install jfrog-cli-go
      # displayName: Install JFrog CLI  
    # - script: jfrog --version

# - job: B
  # dependsOn: A
  # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  # steps:
  # - script: echo this only runs for master