variables:
  GOBIN:  "$(GOPATH)/bin" # Go binaries path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GO111MODULE: "on"
  MODULEPATH: "$(GOPATH)/src/github.com/$(build.repository.name)"
  BIN: $(Build.DefinitionName)
  VER: $(Build.SourceBranchName)
  PLAT: $(System.Phasename)
  BT_API: https://api.bintray.com/content
  BT_REPO: public-generic
  BT_URL: $(BT_API)/$(BT_USER)/$(BT_REPO)/$(BIN)/$(VER)/$(PLAT)/$(UP_FILE)
  
trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']
    
jobs:
  - job: windows_x64
    variables: 
      OUT_FILE: $(BIN).exe
      UP_FILE: $(BIN).exe
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - script: powershell -Command "write-host %0;get-content %0"
        displayName: print tmp script
  - job: macos_x64
    variables: 
      FILE: $(BIN).exe
    pool:
      vmImage: "macOS-10.13"
    steps:
      - script: powershell -Command "write-host $0;get-host"
        displayName: print tmp script
  - job: linux_x64
    variables: 
      FILE: $(BIN).exe
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - powershell: get-host
      - script: ./powershell -command "write-host $0;get-host"
        displayName: print tmp script
