variables:
  GOBIN:  "$(GOPATH)/bin" # Go binaries path
  GOPATH: "$(system.defaultWorkingDirectory)/gopath"
  GO111MODULE: "on"
  modulePath: "$(GOPATH)/src/github.com/$(build.repository.name)"

jobs:
- job: Windows
  pool:
    vmImage: "vs2017-win2016"
  steps:
    - script: echo %Build_SourceBranch%
      displayName: echo  
    - script: go --version
      displayName: go_version
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags')

# - job: Linux
  # pool:
    # vmImage: "ubuntu-16.04"
  # steps:
    # - script: curl -fL https://getcli.jfrog.io | sh
      # displayName: Install JFrog CLI
    # - script: ./jfrog --version
    

# - job: macOS
  # pool:
    # vmImage: "macOS-10.13"
  # steps:
    # - script: brew install jfrog-cli-go
      # displayName: Install JFrog CLI  
    # - script: jfrog --version

# - job: B
  # dependsOn: A
  # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  # steps:
  # - script: echo this only runs for master